services:
  catalogue.db:
    image: postgres

  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalogue.API/Dockerfile

  basket.db:
    image: postgres

volumes:
  postgres_catalogue:
  postgres_basket:

