services:
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      -  "6379:6379"

  #catalogue microservice
  catalogue.db:
    container_name: catalogue.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogueDB
    restart: always
    ports:
      -  "5432:5432"
    volumes:
      - postgres_catalogue:/var/lib/postgresql/data/

  catalogue.api:
    container_name: catalogue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogue.db;Port=5432;Database=CatalogueDB;Username=postgres;Password=postgres
    depends_on:
      - catalogue.db
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  #basket microservice
  basket.db:
    container_name: basket.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDB
    restart: always
    ports:
      -  "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basket.db;Port=5432;Database=BasketDB;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
    depends_on:
      - basket.db
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  #discount microservice
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discount.db
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  #ordering microservice
  order.db:
    container_name: order.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ABcdE123456
    restart: always
    ports:
      - "1433:1433"